# Site settings
title: True Happiness
header-img: img/home-bg.jpg
email: laohasongkram.supakorn@gmail.com
description: "This website is a blog I share for others to learn more about how to become happier in life."
baseurl: ""
url: "http://true-happiness.github.io"
twitter_username: klaoha06
github_username:  klaoha06
facebook_username:  supakorn.laohasongkram

# Build settings
gems: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-feed']
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 7
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
collections: 
- principles