# Site settings
title: True Happiness
header-img: "img/logo.png"
header-author: "Supakorn Laohasongkram"
email: laohasongkram.supakorn@gmail.com
description: "Learn the science and practice of how to truly be happy at True Happiness."
baseurl: ""
url: "http://true-happiness.github.io"
logo: "/img/logo-fb.png"

twitter_username: klaoha06
github_username:  klaoha06
facebook_username:  true-happiness.github.io
wordpress_url: https://truehappinessnow.wordpress.com/

# Build settings
gems: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-feed']
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 7
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
collections: 
- principles